pebblo/reports/html_to_pdf_generator/report_generator.py
Added UTC to local timezone conversion for createdAt timestamp
=> Added UTC to local timezone conversion

pebblo/app/service/service.py
Report file path would be generated at `~/.pebblo/<app-name>/<load-id>/pebblo_report.pdf` and `~/.pebblo/<app-name>/pebblo_report.pdf`
=> Report file path changes

pyproject.toml
Add python-dateutil==2.8.2 to pyproject.toml
=> Add Dateutil dependency

.github/workflows/pypi_release.yml
changes to match the git tag version with pyproject.toml
=> pypi published failed on version mismatch

.github/workflows/linting_skipper.yml, .github/workflows/tests.yml, .github/workflows/tests_skipper.yml, pebblo/tests/test_requirements.txt
- includes the workflow for unit tests 
- added test requirements.txt
=> Added workflow for Unit tests

pyproject.toml
updated the pyproject.toml for version 0.1.7
=> Release 0-1-7

pebblo/app/libs/logger.py, pebblo/app/service/service.py, pebblo/app/utils/utils.py, pebblo/entity_classifier/entity_classifier.py, pebblo/topic_classifier/libs/logger.py
- Moved some debug logs to info
- Set default logging level to info
=> Logging Changes

pebblo/app/service/service.py, tests/app/test_daemon.py
Unit tests and API response changes. 
Test report: 
[test-report.pdf](https://github.com/daxa-ai/pebblo/files/14139058/test-report.pdf)
=> Unit tests and API response changes

pyproject.toml
Release v0.1.9.
* Support for additional Python versions by @Raj725 in https://github.com/daxa-ai/pebblo/pull/96
* [Docs] Update discord to never expire link by @sridhar-daxa in https://github.com/daxa-ai/pebblo/pull/101
* Unit tests and API response changes by @Raj725 in https://github.com/daxa-ai/pebblo/pull/100
=> Release v0.1.9

pyproject.toml
(PyPi) Add more Python versions to support the list
=> Add more Python versions to support the list

.github/workflows/pypi_release.yml
check the test.pypi package installation before publishing to main pypi
=> Updated the workflow for checking test.pypi package install 

pebblo/topic_classifier/config.py, pebblo/topic_classifier/topic_classifier.py, pyproject.toml, tests/topic_classifier/test_topic_classifier.py
Topic classifier: chop off the lower end (16 chars or less)
=> Topic classifier: chop off lower end 16 chars or less

pyproject.toml
=> Release v0.1.10

pebblo/app/models/models.py, pebblo/app/service/discovery_service.py, pebblo/app/service/doc_helper.py, pebblo/reports/templates/reportTemplate.html, tests/app/service/test_loader_doc.py
- Pydantic datetime fix, to use current time.
- Fix for file count with findings per label.
- Key change in report for files with findings.
=> Shreyas pydentic datetime fix

pebblo/app/service/doc_helper.py, pebblo/app/service/service.py
=> LoadHistory Path Fix and log change

pebblo/topic_classifier/enums/constants.py, pebblo/topic_classifier/topic_classifier.py
- Updated topic list 
- Fixed min input length condition for topic classification
=> Updated topic list & Fixed min input length condition 

pebblo/app/daemon.py
Log improvements as per latest comments.
cc: @srics / @shreyas-damle
=> log further improvements.

docs/gh_pages/docs/troubleshooting.md
ref: https://github.com/daxa-ai/pebblo/issues/119
Signed-off-by: Rahul Tripathi [[rahul.psit.ec@gmail.com](mailto:rahul.psit.ec@gmail.com)]
=> fix review comments in PR: 154

CONTRIBUTING.md, docs/gh_pages/development.md, docs/gh_pages/docs/daemon.md, docs/gh_pages/docs/development.md, docs/gh_pages/docs/rag.md, docs/gh_pages/docs/reports.md, docs/gh_pages/docs/troubleshooting.md, docs/gh_pages/rag.md, docs/gh_pages/reports.md, docs/gh_pages/sidebars.ts, pebblo/reports/templates/index.css, pebblo/reports/templates/xhtml2pdfTemplate.html
=> Spellcheck on docs

pebblo/app/daemon.py
ref: https://github.com/daxa-ai/pebblo/issues/163
=> suppress progress bar in --help option.

pyproject.toml
Update version 0.1.10 -> 0.1.11
=> Update version 0.1.10 -> 0.1.11

pebblo/app/api/local_ui_api.py, pebblo/app/pebblo-ui/src/components/index.js, pebblo/app/pebblo-ui/src/pages/index.js, pyproject.toml
=> Added Fix for UI side and Updated toml file

pebblo/app/service/local_ui_service.py
#Was using old key's updated them with latest json.
```json
{
"name": "acme-corp-rag-1",
"load_ids": [
"84e24489-c0d2-49e1-bded-33dff03daa52",
"6621dbbe-3f70-47e4-8517-80bca1ce8f71"
]
}
```
=> Updated old key's  with new one's

pebblo/app/api/local_ui_api.py, pebblo/app/models/models.py, pebblo/app/service/local_ui_service.py
=> Added DataSources Details for Dashboard Tabs

pebblo/app/service/local_ui_service.py, pebblo/app/utils/utils.py
- Removed findingsSummary
- Removed Snippet
```json
[
{
"name": "CSVLoader",
"sourcePath": "/Users/shreyasdamle/work/cloud_defense/rag_apps/openginie_csv/data/sens_data.csv",
"sourceType": "file",
"sourceSize": 2092,
"totalSnippetCount": 9,
"displayedSnippetCount": 9,
"findingsSummary": [
{
"labelName": "Credit card number",
"findings": 1,
"findingsType": "entities",
"snippetCount": 1,
"fileCount": 1
},
{
"labelName": "Medical Advice",
"findings": 7,
"findingsType": "topics",
"snippetCount": 7,
"fileCount": 1
},
{
"labelName": "Harmful Advice",
"findings": 1,
"findingsType": "topics",
"snippetCount": 1,
"fileCount": 1
}
],
"findingsDetails": [
{
"labelName": "Credit card number",
"findings": 1,
"findingsType": "entities",
"snippetCount": 1,
"fileCount": 1,
"snippets": [
{
"snippet": …
```
=> Adding only required values for dataSources

pebblo/app/api/local_ui_api.py, pebblo/app/enums/enums.py, pebblo/app/pebblo-ui/index.html, pebblo/app/pebblo-ui/src/components/applicationList.js, pebblo/app/pebblo-ui/src/constants/constant.js, pebblo/app/pebblo-ui/src/constants/routesConstant.js, pebblo/app/pebblo-ui/src/pages/appDetailsPage.js, pebblo/app/pebblo-ui/src/util.js, pebblo/app/routers/local_ui_routers.py
- `/pebblo` Prefix added to local ui routes.
- Routes for local ui web components fixed.
=> Local UI routes fixes

pebblo/app/service/local_ui_service.py, pebblo/app/utils/utils.py
`ERROR:  Error in Dashboard app Listing. Error:[Errno 20] Not a directory: '/Users/dskumar/.pebblo/.DS_Store//metadata/metadata.json'`
=> Added check for hidden folder

pebblo/reports/templates/xhtml2pdfTemplate.html
Update field from data.reportSummary.filesWithRestrictedData to data.reportSummary.filesWithFindings
=> Update field in xhtml2pdf template for findings

pebblo/app/service/local_ui_service.py
Added Exception handling at per app level.
#####
```
-ERROR:    Error in Dashboard app Listing. Error:'bool' object has no attribute 'get'
-Error in Dashboard app Listing. Error:[Errno 2] No such file or directory: '/Users/shreyasdamle/.pebblo_new_1'
```
=> Exception handling per app

pebblo/app/config/service.py
This fixes blank page issue with 307 and/or 304 status code.
Tested this locally in chrome regular mode as well as on incognito mode.
=> Local UI Loading issue fixed

pebblo/app/api/local_ui_api.py, pebblo/app/routers/local_ui_routers.py, pebblo/app/service/local_ui_service.py, pebblo/app/utils/utils.py
- Ruff fixes for new files added for local UI feature
- Replaced error with warning in get apps API.
=> Ruff fixes for new files added for local UI feature

pebblo/app/routers/local_ui_routers.py
- Response class fixed for `/report` api `local-ui`.
=> [Fix] Response class fixed for file response local ui

pebblo/app/pebblo-ui/src/components/snippetDetails.js, pebblo/app/pebblo-ui/src/constants/constant.js, pebblo/app/pebblo-ui/static/index.css
- Snippet count fixed for app details page.
- Data mapping fixed for data source table on app details page.
- Load history overflowing table content fixed.
=> [Fix] local ui app details page snippet count fixed

Makefile, pebblo/topic_classifier/config.py, pebblo/topic_classifier/enums/constants.py
- Update Pebblo topic classifier to version V8
- Update make command to display slowest 10 unit tests
=> Update Pebblo topic classifier to version V8

docs/gh_pages/docs/config.md, docs/gh_pages/docs/installation.md, docs/gh_pages/docs/pebblo_ui.md, docs/gh_pages/sidebars.ts
- Pebblo UI documentation added.
=> [Update] Pebblo UI documentation added.

pyproject.toml
Added icons file path for pebblo local UI in pyproject.toml
=> Added file path for icons

pebblo/app/service/local_ui_service.py
Fix for app getting disappeared from local UI while execution is in progress
=> Fix for app getting disappeared from local UI while execution is in progress

docs/gh_pages/docs/config.md, docs/gh_pages/docs/development.md, docs/gh_pages/docs/installation.md, pebblo/app/config/service.py, pebblo/app/exceptions/exception_handler.py, pebblo/app/service/service.py, pebblo/reports/html_to_pdf_generator/generator_functions.py, pebblo/reports/html_to_pdf_generator/report_generator.py, pebblo/reports/reports.py, pyproject.toml, tests/app/config/test_config_validation.py, tests/app/test_daemon.py
**Changes:**
- Removed Pango dependency by removing weasyprint from pyproject.toml
- Moved imports within respective functions, so that it does not give error unless user puts renderer as weasyprint without installing pango and weasyprint.
- Added changes to documentation to install weasyprint and pango separately.
**Testing done:**
- With default value of html2pdf:
```
(venv-local) ➜  pebblo git:(shreyas-remove-pango) ✗ pebblo --config pebblo/app/config/config.yaml
Downloading topic, entity classifier models ...
Initializing topic classifier ...
Initializing topic classifier ... done
Initializing entity classifier ...
Initializing entity classifier ... done
Pebblo server starting ...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████ …
```
=> Remove pango dependency

Makefile, pyproject.toml
- updated the project.toml to use MyPy config
=> MyPy Config Changes

pebblo_saferetriever/langchain/identity-rag/google_auth.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag-pinecone.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag-qdrant.py, pebblo_saferetriever/langchain/identity-rag/pinecone_data_loader.py, pebblo_saferetriever/langchain/identity-rag/requirements.txt
- Switch the sample app to use Qdrant(in memory) with the collection name
- Sample app with Pinecone
=> Switch sample app to use Qdrant(in memory) with collection name

pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag-pinecone.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag-qdrant.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py, pebblo_saferetriever/langchain/identity-rag/requirements.txt
Added folder id and requirements
=> Added folder id and requirements

docs/gh_pages/docs/installation.md, pebblo/app/pebblo-ui/static/index.css
=> Fix spelling errors

pebblo_saferetriever/README.md, pebblo_saferetriever/langchain/identity-rag/google_auth.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py
**Note:** This has changes in the common method in `pebblo_saferetriever/langchain/identity-rag/google_auth.py` file. If these changes are merged the other 2 apps also needs to be fixed to get those working.
This includes below fixes to the identity based RAG app:
- Added inputs for ingestion user and end user.
- Added instructions in the README.md file.
Sample output:
```
(venv) ➜  identity-rag git:(shreyas-rag-app-fixes) ✗ python3 pebblo_identity_rag.py
Please enter ingestion user details for loading data...
email address : arpit@clouddefense.io
service-account.json path : credentials/service-account.json
Folder id : 1sRvP0j6L6M_Ll0y_8Qp7cFWUOlpdbfN5
Loading RAG documents ...
Unable to reach pebblo server.
None
Loaded 117 documents ...
Hydrating Vector DB ...
Finished hydrating Vector …
```
=> RAG App Fixes

pebblo/app/pebblo-ui/src/components/snippetDetails.js, pebblo/app/pebblo-ui/src/constants/constant.js
Updated Snippet details UI:
1. Added Showing - out of - snippets text.
2. Show total count on snippets tab
=> Updated Snippet tab in Pebblo UI

pebblo_safeloader/langchain/identity-rag/pebblo_identity_safeload.py, pebblo_saferetriever/langchain/identity-rag/google_auth.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py
Fix formatting & lint errors. Code cleanup.
=> Fix formatting & lint errors. Code cleanup.

pebblo/app/pebblo-ui/src/constants/constant.js, pebblo/app/pebblo-ui/src/pages/appDetailsPage.js
Handle values of displayedSnippetCount, totalSnippetCount, findingsDetails if keys do not exist in datasources[0]
=>  Pebblo UI - Handle null states for objects

.github/workflows/docker_release.yml, docker/Dockerfile.base, docker/docker-bake.hcl
- dockerifile 
- docker build image and publish to docker hub 
- git workflow
=> Added changes for Docker image 

.github/workflows/docker_release.yml, docker/Dockerfile.base, docker/config.yaml
- added changes for default  config.yaml
- updated workflow docker build and push
=> Docker config pebblo

pebblo/app/models/models.py, pebblo/app/service/discovery_service.py, pebblo/app/service/doc_helper.py, pebblo/app/service/local_ui_service.py, pebblo/app/utils/utils.py, tests/app/test_utils.py, tests/test_requirements.txt
**Description:**  Adding pebblo client and sever version to show in local UI as well as reports
**Testing:** Tested by checking values in report.json created
**Note:** UI changes and testing is in progress
=> Adding pebblo client as well as server version for local UI and reports

pebblo/app/pebblo-ui/src/pages/index.js
Tested locally by building UI.
Bubble chart is not working but UI is up.
=> Fixed breaking Local UI

docker/config.yaml
- added the logging level : info in default config file
=> Docker: Update logging level to Info

pebblo/app/pebblo-ui/src/constants/constant.js
Removed text capitalize on file name in local UI
=> Removed text capitalize on file name in local UI

pebblo/app/service/discovery_service.py
One test case was failing after app discover API changes that I made yesterday. Fixed the code and now all test cases are passing.
=> Test Case Fix

docker/docker-bake.hcl
1. Fixed docker push repo
2. removed base prefix from tags
=> Docker repo fix

pebblo/app/api/api.py, pebblo/app/exceptions/exception_handler.py, pebblo/app/models/models.py, pebblo/app/routers/routers.py, pebblo/app/service/prompt_service.py, pebblo/app/utils/utils.py, tests/app/test_app_prompt.py, tests/app/test_prompt_api.py
**Description:** _/v1/prompt_ for adding data in SafeRetrieval Part in local UI.
**Changes done:**
1. Added new API: _/v1/prompt_. Payload for this API:
<details>
<summary>Payload</summary>
```python
{
"name": "acme-corp-rag-123",
"context": {
"retrieved_from": [
"test_data.pdf"
],
"doc": "Sachin's SSN is 222-85. His AWS Access Key is: AKIPT4PDORIRTV6PH. His Passport ID is 5484880UA. And Github Token is: ghpu657yiujgwfrtigu3ver238765tyuhygvtrder6t7gyvhbuy5e676578976tyghy76578uygfyfgcyturtdf",
"vector_db": "ChromaDB"
},
"prompt": {
"data": "What is Sachin's Passport ID?"
},
"response": {
"data": "His passport ID is 5484880UA."
},
"prompt_time": "Wed 17 Apr, 2024, 15:03 PM",
"user": "dristy"
}
```
</details>
2. New file is created in metadata folder: **app_metadata.json**, where retriever …
=> Adding /v1/prompt API for Safe Retrieval part

pebblo/app/models/models.py, pebblo/app/service/local_ui_service.py
**Issue:** https://github.com/daxa-ai/pebblo/issues/342
Solving first two points of above mention issue
**Changes:** Updated payloads:
**Description:** _/v1/prompt_ for adding data in SafeRetrieval Part in local UI.
**Changes done:**
1. App Listing Payload:
<details>
<summary>payload</summary>
```python
{
"pebbloServerVersion": "0.1.14",
"loaderApps": {
"applicationsAtRiskCount": 5,
"findingsCount": 51,
"documentsWithFindingsCount": 5,
"dataSourceCount": 5,
"appList": [
{
"name": "new-app",
"topics": 3,
"entities": 9,
"owner": "James Bond",
"loadId": "a14ce88b-98ad-4a03-accb-6fe243cb29ef"
},
{
"name": "acme-corp-rag-123323",
"topics": 0,
"entities": 9,
"owner": "Joe Smith",
"loadId": "ebf28eb2-01f7-471f-85f1-cfefb1bc1d50"
},
{
"name": "plugin_version_test",
"topics": 0,
"entities": 9, …
```
=> Dristy local UI api update

pebblo_cloud/langchain/rag-sample/semantic_rag_sample.py, pebblo_saferetriever/README.md, pebblo_saferetriever/langchain/identity-n-semantic-rag/.gitignore, pebblo_saferetriever/langchain/identity-n-semantic-rag/README.md, pebblo_saferetriever/langchain/identity-n-semantic-rag/google_auth.py, pebblo_saferetriever/langchain/identity-n-semantic-rag/requirements.txt, pebblo_saferetriever/langchain/identity-n-semantic-rag/semantic_rag.py, pebblo_saferetriever/langchain/identity-n-semantic-rag/utils.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py
Update Identity and Semantic enforcement samples
=> Update Identity and Semantic enforcement samples

CONTRIBUTING.md, Makefile
**Description:**
Added the formatting commands (`format` and `format_diff`) to use the `ruff` formatting tool. 
**Issue:** https://github.com/daxa-ai/pebblo/issues/341
**Sample output:**
=> Added make command to format all/changed files

pebblo/app/service/discovery_service.py, tests/app/service/test_discovery.py
Added unit tests for app discovery API
=> Added unit tests for app discovery API

docs/gh_pages/docs/rag.md
Add PEBBLO_CLASSIFIER_URL env param details to https://daxa-ai.github.io/pebblo/rag page
=> Update rag.md for pebblo environment variable

pebblo_cloud/langchain/rag-sample/semantic_rag_sample.py, pebblo_saferetriever/README.md, pebblo_saferetriever/langchain/identity-n-semantic-rag/.gitignore, pebblo_saferetriever/langchain/identity-n-semantic-rag/README.md, pebblo_saferetriever/langchain/identity-n-semantic-rag/google_auth.py, pebblo_saferetriever/langchain/identity-n-semantic-rag/requirements.txt, pebblo_saferetriever/langchain/identity-n-semantic-rag/semantic_rag.py, pebblo_saferetriever/langchain/identity-n-semantic-rag/utils.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py
- Combined sample for Identity and Semantic enforcement 
- Updated PebbloRetrievalQA initialization per new Langchain PR
=> Update Identity and Semantic enforcement samples (PebbloRetrievalQA)

pebblo/app/config/config.py, pebblo/app/service/discovery_service.py, pebblo/app/service/doc_helper.py, pebblo/app/service/local_ui_service.py, pebblo/app/service/prompt_service.py, pebblo/app/utils/utils.py, tests/app/service/test_loader_doc.py
Fixed easy linter fixes.
Before this fix: https://github.com/daxa-ai/pebblo/actions/runs/8834624555/job/24256751456?pr=353
```
Found 35 errors in 16 files (checked 84 source files)
pebblo/reports/html_to_pdf_generator/report_generator.py:58: error: No overload variant of "__getitem__" of "list" matches argument type "str"  [call-overload]
pebblo/reports/html_to_pdf_generator/report_generator.py:58: note: Possible overload variants:
pebblo/reports/html_to_pdf_generator/report_generator.py:58: note:     def __getitem__(self, SupportsIndex, /) -> Any
pebblo/reports/html_to_pdf_generator/report_generator.py:58: note:     def __getitem__(self, slice, /) -> list[Any]
tests/topic_classifier/test_topic_classifier.py:154: error: Need type annotation for "mock_response"  [var-annotated] …
```
=> Linter fixes

pebblo/app/service/local_ui_service.py
This fixes minor review comment fixes in https://github.com/daxa-ai/pebblo/pull/353
=> Review comment fixes

pebblo/app/models/models.py, pebblo/app/service/local_ui_service.py, pebblo/app/service/prompt_service.py, tests/app/test_prompt_api.py
**Description:** Updating App Details API for local UI. Also updated prompt service with new field `user_identities`
**Changes:** 
1. active_users and documents response is updated.
Now active users will have: `retrievals`, `last accessed time` and `linked groups`
and documents will have `retrievals` and `last accessed time`
2. new field will be updated in app_metadata.json `linked_groups`
=> Updating active_users and document response for app details api

pebblo/app/pebblo-ui/src/components/index.js, pebblo/app/pebblo-ui/src/components/progressBar.js, pebblo/app/pebblo-ui/src/components/viewMore.js, pebblo/app/pebblo-ui/src/constants/constant.js, pebblo/app/pebblo-ui/src/util.js, pebblo/app/pebblo-ui/static/index.css
Added Active Users & Documents Tab on App Details Page:
1. 
2.
=> Active Users & Documents Tabs for App Details

.github/workflows/tests.yml
- tests/**/*.py trigger on change
=> Unit test trigger on tests

tests/app/service/test_discovery.py
After version change in pyproject.toml, one unit test was failing. Fixed it. Tested locally, working fine.
=> Pebblo server version UT fix

pebblo/app/pebblo-ui/src/components/retrievalDetails.js, pebblo/app/pebblo-ui/src/components/snippetDetails.js, pebblo/app/pebblo-ui/src/constants/constant.js
1. Add reverse ordering based on time to Retrievals in App details.
2. Handle undefined string by replacing with "-".
3. Remove first letter capitalize on file and owner strings
4. Add Response text in Retrieval Tab:
=> Fix Local UI issues

pebblo/app/pebblo-ui/src/constants/constant.js, pebblo/app/pebblo-ui/src/pages/appDetailsPage.js, pebblo/app/pebblo-ui/src/pages/safeRetrievalAppDetails.js, pebblo/app/pebblo-ui/src/util.js
Capitalize first letter of all App names across Local UI
=> Capitalize app names for local UI

pebblo/app/service/discovery_service.py, pebblo/reports/html_to_pdf_generator/report_generator.py, tests/app/service/test_discovery.py, tests/app/service/test_loader_doc.py
- Updated one UT to be independent on pebblo version. Here Pebblo Server version is mocked.
- Fixed some linting issues.
=> Updated UT and minor linting fixes

README.md, docs/gh_pages/docs/rag.md, pebblo_cloud/langchain/README.md, pebblo_cloud/langchain/rag-sample/requirements.txt, pebblo_safeloader/README.md, pebblo_safeloader/langchain/acme-corp-rag/acme_corp_rag.py, pebblo_safeloader/langchain/acme-corp-rag/acme_corp_rag_pebblo.py, pebblo_safeloader/langchain/acme-corp-rag/requirements.txt, pebblo_saferetriever/README.md, pebblo_saferetriever/langchain/identity-n-semantic-rag/requirements.txt, pebblo_saferetriever/langchain/identity-n-semantic-rag/semantic_rag.py, pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py, pebblo_saferetriever/langchain/identity-rag/requirements.txt, pebblo_saferetriever/langchain/semantic-rag/requirements.txt, tests/integration/samples/pebblo_csv_loader/pebblo_csvloader.py
Update Langchain library versions and imports in the sample apps
=> Update langchain library versions and imports in the sample apps

docs/gh_pages/docs/retrieval_chain_semantic_enf.md
Add docs for Semantic Enforcement RAG using PebbloRetrievalQA
=> Add docs for Semantic Enforcement RAG using PebbloRetrievalQA

docs/gh_pages/docs/safe_loader_samples.md, docs/gh_pages/docs/safe_retriever_samples.md, docs/gh_pages/sidebars.ts
=> Index for sample apps

pebblo/app/models/models.py, pebblo/app/service/prompt_service.py, tests/app/test_prompt_api.py
This contains below changes:
- Regression issue fix - where retrieval app page was blank.
=> Fix for blank retrieval app page

pebblo/app/models/models.py, pebblo/app/service/local_ui_service.py, pebblo/app/service/prompt_service.py, tests/app/test_prompt_api.py
- Sort Apps on app listing page based on findings.
- Removed topic classification from prompt.
=> Sort Apps on app listing page based on findings

pebblo/app/config/config.py, pebblo/app/daemon.py, pebblo/app/utils/version.py
Find pebblo pkg version and display during
server startup.
Add CLI arg "--version" / "-v" to just display
version and exit
=> Display pebblo version

pebblo/app/pebblo-ui/src/components/deleteApp.js, pebblo/app/pebblo-ui/src/components/index.js, pebblo/app/pebblo-ui/src/icons/index.js, pebblo/app/pebblo-ui/src/pages/appDetailsPage.js, pebblo/app/pebblo-ui/src/pages/safeRetrievalAppDetails.js
- Enable delete app feature for retrieval apps:
_Turned delete app into a common component to be used at both safe loader & retrieval app details pages._
=> Delete App for Retrieval Apps

pebblo/app/service/local_ui_service.py
Updated log messages:
- Added `[Dashboard]`, `[App Details]` and `[Delete App]` identifiers to identify the page from where the message was originated.
- Made messages more specific and unique so that we can identify exact location easily.
Sample logs:
```
DEBUG:    [Dashboard]: Metadata file path ~/.pebblo/shreyas-test-dir//metadata/metadata.json
DEBUG:    Reading content from file: ~/.pebblo/shreyas-test-dir//metadata/metadata.json
DEBUG:    Exception: File not found at path /Users/shreyasdamle/.pebblo/shreyas-test-dir//metadata/metadata.json
DEBUG:    [Dashboard]: Metadata file /metadata/metadata.json not found for app: shreyas-test-dir.
WARNING:  [Dashboard]: Metadata file is not present for application: shreyas-test-dir,skipping application
```
=> Log messages updated

pebblo/app/service/local_ui_service.py
- App details page: Sorting of retrievals based on time
- Retreival App Listing Page: App Sorting of apps based on retrieval count:
=> Sort prompt retrievals based on time

pebblo/app/pebblo-ui/src/components/progressBar.js, pebblo/app/pebblo-ui/src/constants/constant.js
- Update Pebblo Client Key on App Instance Details Pane:
Show client name and version
- Remove unused console.log
=> Update Pebblo client key

pebblo/app/pebblo-ui/src/components/progressBar.js, pebblo/app/pebblo-ui/src/constants/constant.js
=> Revert "Update Pebblo client key"

.github/workflows/integration_run.yml
Replaced console logs to file logs for verification.
=> Integration test fix

pebblo/app/pebblo-ui/src/components/snippetDetails.js, pebblo/app/pebblo-ui/src/components/tooltip.js, pebblo/app/pebblo-ui/static/index.css
Confidence Score for Topic:
Confidence Score for Entity:
=> Confidence score UI

pebblo/app/config/config.yaml, pebblo/app/service/discovery/discovery_service.py, pebblo/app/service/loader/document/document.py, pebblo/app/service/loader/loader_doc_service.py, pebblo/app/service/loader/snippet/snippet.py, pebblo/app/service/prompt/prompt_service.py
- Fixed issues in loader/doc found while testing.
- Removed location and name fields from config.yaml as we have not handled them fully yet.
=> Sqlite Fixes

pebblo/app/models/db_models.py, pebblo/app/service/local_ui/retriever_apps.py, pebblo/app/service/local_ui_service.py, pebblo/app/service/prompt/prompt_service.py, pebblo/app/storage/database.py, pebblo/app/storage/sqlite_db.py, tests/entity_classifier/test_entity_classifier.py
=> Adding details as well as delete APIs for Retriever  DB Apps

pebblo/app/models/models.py, pebblo/app/pebblo-ui/src/components/snippetDetails.js, pebblo/app/pebblo-ui/src/components/tooltip.js, pebblo/app/pebblo-ui/static/index.css, pebblo/app/service/doc_helper.py, pebblo/app/service/prompt_gov.py, pebblo/app/service/prompt_service.py, pebblo/entity_classifier/README.md, pebblo/entity_classifier/entity_classifier.py, pebblo/entity_classifier/utils/config.py, pebblo/entity_classifier/utils/regex_pattern.py, pebblo/entity_classifier/utils/utils.py, pebblo/topic_classifier/README.md, pebblo/topic_classifier/topic_classifier.py, pebblo/utils.py, tests/app/service/test_loader_doc.py, tests/app/service/test_prompt_gov.py, tests/app/test_prompt_api.py, tests/entity_classifier/mock_response.py, tests/entity_classifier/test_data.py, tests/entity_classifier/test_entity_classifier.py, tests/test_utils.py, tests/topic_classifier/test_topic_classifier.py
Features added in this PR:
- Adding confidence score to snippets.
- Entity groups
=> Pebblo 0.1.18 to main

pebblo/app/service/discovery/discovery_service.py, pebblo/app/service/loader/loader_doc_service.py
- Added loader/doc response in case of db as a storage.
- Updated /discovery response in case of db as a storage.
=> Loader doc db response

pebblo/reports/html_to_pdf_generator/report_generator.py
Updated client version fetch property to `versionObj.get("version", None) `
=> Fixed version error in case of empty clientVersion

pebblo/app/service/discovery/common.py, pebblo/app/service/loader/loader_doc_service.py, pebblo/app/service/local_ui/loader_apps.py, pebblo/app/storage/sqlite_db.py
- Fixed loader/doc issues w.r.t. loadId
- Moved commit before pdf generation
- Updated query filter, to get latest id
=> Fixed loader/doc issues w.r.t. loadId

pebblo/app/service/loader/loader_doc_service.py, pebblo/reports/html_to_pdf_generator/report_generator.py
1. To check if version is not defined and is coming as {} while report generation
2. While getting data source, need to fetch first value from query response
=> Fixing loader API changes

.github/workflows/tests.yml, pebblo/app/service/service.py
Added new version - python 3.12.5 for UTs.
=> Added new version - python 3.12.5 for UTs

pebblo/app/config/config.py, pebblo/app/models/db_models.py, pebblo/app/models/db_response_models.py, pebblo/app/models/models.py, pebblo/app/service/discovery_service.py, pebblo/app/service/doc_helper.py, pebblo/app/service/local_ui_service.py, pebblo/app/service/prompt_gov.py, pebblo/app/service/prompt_service.py, pebblo/app/service/service.py, pyproject.toml, tests/app/service/test_discovery.py, tests/app/test_prompt_api.py
- Updated all model files needed due to pydantic upgrade.
- Pinned pydantic and pydantic-settings versions to their latest versions.
Tested locally with csv loader and directory loader.
Notes:
- Did these code changes with the pydantic migration tool - https://docs.pydantic.dev/latest/migration/#code-transformation-tool
- Pydantic is planning for v3 release and are planning to deprecate some functionality. For example .dict() will be deprecated in v3. So pinned these versions to avoid problems due to pydantic release.
=> Updated pydantic version and relevant model changes

docs/gh_pages/docs/entityclassifier.md, docs/gh_pages/docs/pebblo_ui.md, docs/gh_pages/docs/safe_loader.md, docs/gh_pages/docs/topicclassifier.md, pebblo/entity_classifier/README.md, pebblo/topic_classifier/README.md
**Changes:**
- Added docs for pebblo-0.1.18 version.
- Updated confidence score changes.
- Updated Entity classifier with new entity `IP Address`
- Updated Topics which we are supporting currently
=> Updated doc for 0.1.18 version

docs/gh_pages/docs/config.md, docs/gh_pages/docs/daemon.md, docs/gh_pages/docs/development.md, docs/gh_pages/docs/entityclassifier.md, docs/gh_pages/docs/installation.md, docs/gh_pages/docs/introduction.md, docs/gh_pages/docs/llama_index_safe_reader.md, docs/gh_pages/docs/rag.md, docs/gh_pages/docs/reports.md, docs/gh_pages/docs/retrieval_chain.md, docs/gh_pages/docs/safe_retriever.md, docs/gh_pages/docs/safe_retriever_samples.md, docs/gh_pages/docs/topicclassifier.md, docs/gh_pages/docs/troubleshooting.md, docs/gh_pages/docusaurus.config.ts
=> Update Pebblo Docs Footer

pebblo/app/utils/utils.py
With logging as info, local ui is not getting loaded, due to the issue in handling of timeit. Fixed with this code change.
=> Fixed timeit issue

.github/workflows/pypi_release.yml, .github/workflows/test_pypi_release.yml, pyproject.toml
Fixes the following Dependabot issues:
- https://github.com/daxa-ai/pebblo/security/dependabot/34
- https://github.com/daxa-ai/pebblo/security/dependabot/35
=> Dependabot fixes

pebblo/app/pebblo-ui/src/constants/constant.js
- Show zero values if they are present:
- Share '-' if keys are not present in JSON:
=> Show zero state for App Finding tabs

pebblo/app/pebblo-ui/src/components/table.js
Show 0 in tables where value exists:
=> Show zero in tables on Local UI

.github/workflows/docker_release.yml, deploy/docker/docker-bake.hcl
This reverts commit 15857e81cdf172a257534059c2287d2108b7f66e. 
This reverts commit 17a2bf79bc6bec1c4842df74effd3613b8ccd01f. 
This reverts commit 89a57c10cb7575d163823afd852e77d0a39fe355. 
This reverts commit 717bc4baf1cb57af360750564f43b813943ba614. 
This reverts commit b6b4f7fcdee3b0d541fc79a5cd8ac5c9570e4c1c.
=> Revert docker_release.yml changes

pebblo/app/config/config.yaml
**Change:** Updating location of anonymizeSnippets location from classifier to reports in config.yaml, in this way we can avoid deprecation message if user runs even using config file without changing any value
=> Updated anonymizeSnippets location from classifier to reports in config.yaml

pebblo/app/pebblo-ui/src/constants/keywordMapping.js, pebblo/reports/enums/keyword_mapping.py, pebblo/topic_classifier/config.py, pebblo/topic_classifier/enums/constants.py, tests/app/service/test_doc_helper.py, tests/app/service/test_loader_doc_service.py, tests/app/test_prompt_api.py
App with old classifier
App with new classifier
=> Topic Classifier Changes

tools/Readme.md
Added Readme.md for using pebblo-reporter
=> Added Readme.md for using pebblo-reporter
