- pyproject.toml
Move test dependencies to the `project.optional-dependencies`
> Move test dependencies to project.optional-dependencies

- pebblo/app/service/doc_helper.py
We are moving initialization of EntityClassifier() per API, in order to avoid memory leak issues that were causing due to one time load.
> Slowness partial fix

- pebblo/app/daemon.py
- pebblo/app/service/doc_helper.py
This is issue since we added this `EntityClassifier` initialization in daemon.py, but it was suppressed due to one more import in doc_helper.py at the top. Now we moved that import to inside class, so this is giving issue.
It was not caught in my testing in earlier PR as the model was already present in my venv.
> Fixing entity classifier initialization issue.

- README.md
- pebblo/app/config/config.py
- pebblo/app/config/config.yaml
- pebblo/app/config/service.py
- pebblo/app/daemon.py
- pebblo/app/enums/enums.py
- pebblo/app/libs/logger.py
- tests/app/test_daemon.py
It will use default config details
```
Example:
(venv) PS C:\Users\KunalJadhav\Desktop\Kunal_Desktop\pebblo_6_2_24\pebblo> pebblo                                                             
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
C:\Users\KunalJadhav\Desktop\Kunal_Desktop\pebblo_6_2_24\venv\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pyt
ree_node instead.
_torch_pytree._register_pytree_node(
C:\Users\KunalJadhav\Desktop\Kunal_Desktop\pebblo_6_2_24\venv\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: …
```
> Config.yaml Support for Pebblo

- pebblo/app/service/doc_helper.py
- pebblo/reports/templates/reportTemplate.html
Fix for loadHistory not found in more reports path: Updated data mapping to {{ data.loadHistory.moreReportsPath }}
> Update json mapping for load history 

- pebblo/app/config/config.py
Output without custom config.yaml:
```
pebblo git:(shreyas-log-change) ✗ pebblo
Downloading topic, entity classifier models ...
Initializing topic classifier ...
Initializing topic classifier ... done
Initializing entity classifier ...
Initializing entity classifier ... done
Pebblo server starting ...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:13<00:00,  1.37s/it]
INFO:     Started server process [99401]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
INFO:     App Discover …
```
> Skipped printing config details at the startup

- pebblo/app/config/config.py
- pebblo/app/daemon.py
- pebblo/app/enums/enums.py
- pebblo/app/service/discovery_service.py
- pebblo/app/service/service.py
- pebblo/reports/reports.py
- samples/langchain/acme-corp-rag/acme_corp_rag.py
- samples/langchain/acme-corp-rag/acme_corp_rag_pebblo.py
- tests/app/service/test_loader_doc.py
- Removed unused imports.
- Added `err` to exception message.
- Removed unnccessary `;`
> Resolve ruff lint errors

- docs/gh_pages/development.md
- docs/gh_pages/entityclassifier.md
- docs/gh_pages/installation.md
- docs/gh_pages/sidebars.ts
- docs/gh_pages/topicclassifier.md
> Adding documentation for Pebblo Topic and Entity Classifier

- pebblo/entity_classifier/entity_classifier.py
- pebblo/entity_classifier/utils/config.py
Updated following scores while context matching:
- Entity = "0.8"  # based on this score entity output is finalized.
- EntityMinScore = "0.45"  # It denotes the pattern's strength
- EntityContextSimilarityFactor = "0.35"  # It denotes how much to enhance confidence of match entity
- EntityMinScoreWithContext = "0.4"  # It denotes minimum confidence score
> Updating scores for entity classifier for context matching

- pebblo/topic_classifier/config.py
- pebblo/topic_classifier/enums/constants.py
- pebblo/topic_classifier/libs/logger.py
- pebblo/topic_classifier/topic_classifier.py
- tests/topic_classifier/test_topic_classifier.py
- Topic Classifier Linting/Formatting fixes
- Added docstrings for all the modules in the Topic classifier
- Defined constants instead of duplicating strings at multiple places
> Topic Classifier Linting/Formatting fixes

- pebblo/app/api/api.py
- pebblo/app/api/local_ui_api.py
- pebblo/app/config/config.py
- pebblo/app/config/service.py
- pebblo/app/daemon.py
- pebblo/app/enums/enums.py
- pebblo/app/routers/routers.py
- pebblo/app/service/discovery_service.py
- pebblo/app/service/doc_helper.py
- pebblo/app/service/local_ui_service.py
- pebblo/app/service/service.py
- pebblo/app/utils/utils.py
- tests/app/service/test_loader_doc.py
- tests/app/test_daemon.py
- Fixed ruff and pylint issues for `pebblo/app` module and `tests/app` module.
- All unit tests are passing.
- There are few ruff fixes showing up on the github workflow, which were not being shown locally. I will fix them in the follow up PR in order to get this PR merged quickly to avoid conflicts for other team members,
> Ruff and pylint fixes for pebblo/app module

- docs/gh_pages/docs/config.md
- docs/gh_pages/docs/entityclassifier.md
- docs/gh_pages/entityclassifier.md
- pebblo/app/config/config.py
- pebblo/app/config/config.yaml
- pebblo/app/enums/enums.py
- pebblo/app/service/doc_helper.py
- pebblo/entity_classifier/README.md
- pebblo/entity_classifier/entity_classifier.py
- pebblo/entity_classifier/utils/config.py
- pebblo/entity_classifier/utils/utils.py
- tests/entity_classifier/mock_response.py
- tests/entity_classifier/test_data.py
- tests/entity_classifier/test_entity_classifier.py
**Requirement:** To anonymize document snippets in Pebblo report. As Pebblo is considered for environments beyond dev, anonymization will help distribute the report to more app stakeholders. 
**Issue Link:** #224 
**Note:**
To use this function:
```
from pebblo.entity_classifier.entity_classifier import EntityClassifier
text = <Document text>
entity_classifier_obj = EntityClassifier()
entities, total_count, anonymized_text = entity_classifier_obj.entity_classifier_obj.presidio_entity_classifier_and_anonymizer(text,anonymize_all_entities)
print(f"Entity Group: {entity_groups}")
print(f"Entity Count: {total_entity_count}")
print(f"Anonymized Text: {anonymized_text}")
```
**Example:**
```
text = """
Hello, My name is John. 
My AWS Access Key is: AKIAQIPT4PDORIRTV6PH
"""
Anomyzed Response: …
```
> Adding document anomyzer

- pebblo/reports/html_to_pdf_generator/report_generator.py
- pebblo/reports/templates/weasyprintTemplate.html
- pebblo/reports/templates/xhtml2pdfTemplate.html
Added current timezone to all date strings in report pdf
Example:
> Added timezone to date strings in report pdf

- docs/gh_pages/docs/config.md
- pebblo/app/config/config.py
- pebblo/app/config/config.yaml
- pebblo/app/config/config_validation.py
- pebblo/app/enums/enums.py
- pebblo/app/service/doc_helper.py
- pebblo/entity_classifier/README.md
- pebblo/entity_classifier/entity_classifier.py
- tests/app/config/test_config_validation.py
- tests/entity_classifier/mock_response.py
- tests/entity_classifier/test_entity_classifier.py
- Updating config value anonymizeAllEntities to anonymizeSnippets.
- New condition added whether to anonymize snippet or not
- Also updated its default value to False, earlier it was true
> Updating config value anonymizeAllEntities to anonymizeSnippets

- pebblo/app/pebblo-ui/src/components/tab.js
- pebblo/app/pebblo-ui/src/components/table.js
- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/app/pebblo-ui/src/pages/appDetailsPage.js
- pebblo/app/pebblo-ui/src/util.js
Add timezone to dates in Pebblo UI:
> Add timezone to local UI dates

- README.md
- changes related to scarf.sh 
- updated the readme to use --extra-index-url https://packages.daxa.ai/simple/ for pip install pebblo
> Update download url for pip install

- README.md
- docs/gh_pages/docs/installation.md
- readme update for pebblo run on docker
> Pebblo Docker README and Installation guide changes  

- pebblo/app/libs/responses.py
- pebblo/app/models/models.py
- pebblo/app/routers/routers.py
- pebblo/app/service/doc_helper.py
- pebblo/app/service/service.py
- tests/app/test_daemon.py
- tests/reports/test_report_generator.py
- tests/reports/test_reports.py
- Updated the response of `loader/doc` API
- Handled response in case of exception
- Updated respective unit test
- Some ruff issues fixed caught while checking locally.
Testing:
- Tested with/without client side changes.
- Verified that report is getting generated as expected.
- Verified local UI is showing individual app and all the apps.
> Loader doc response changes for Pebblo Cloud initial work

- README.md
- updated the readme to install pebblo using *.whl
> Pebblo install using *.whl file download

- pebblo/app/models/models.py
- pebblo/app/service/doc_helper.py
- pebblo/app/utils/utils.py
- tests/app/service/test_loader_doc.py
- These changes add authorized identities in documents with findings section per file and in snippet section per snippet.
- These changes are for local UI as well as for pdf report.
Testing:
- Tested locally and verified that authorized_entities are getting added in top findings and snippets.
- Need to be tested with Local UI after UI changes are done.
> Authorized Identity - backend changes to show authorized identities

- pebblo/app/pebblo-ui/src/components/Dialog.js
- pebblo/app/pebblo-ui/src/components/bubbleChart.js
- pebblo/app/pebblo-ui/src/components/chips.js
- pebblo/app/pebblo-ui/src/components/index.js
- pebblo/app/pebblo-ui/src/components/snippetDetails.js
- pebblo/app/pebblo-ui/src/components/table.js
- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/app/pebblo-ui/src/util.js
- pebblo/app/pebblo-ui/static/index.css
- pebblo/reports/html_to_pdf_generator/report_generator.py
- pebblo/reports/templates/weasyprintTemplate.html
- pebblo/reports/templates/xhtml2pdfTemplate.html
- pebblo_saferetriever/langchain/semantic-rag/pebblo_semantic_rag.py
- pebblo_saferetriever/langchain/semantic-rag/utils.py
- tests/reports/test_report_generator.py
**Added Identity details for Pebblo UI:**
1. Added identity list for findings:
Dialog shows all identities: 
2. Added identity details in snippets:
**Report PDFs:**
- xhtml2pdf Report PDF:
1. Added identity details in Top Findings table:
2. Updated snippets:
- weasyprint Report PDF:
1. Added identity details in Top Findings table:
2. Updated snippets:
> Identity UI added for local ui and reports

- pebblo/app/pebblo-ui/src/components/bubbleChart.js
- pebblo/app/pebblo-ui/src/components/chartCard.js
- pebblo/app/pebblo-ui/static/index.css
1. Updated N snippet count label/index for bubble chart to "Circle size represents the number of snippets".
2. Changed bubble tooltip label from **Snippets** to **Snippet Count.**
3. Updated bubble chart to only show topic/entity name on bubbles having upto **highest two snippet** count values.
> Update bubble chart UI

- pebblo/app/pebblo-ui/src/components/tooltip.js
- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/app/pebblo-ui/static/index.css
1. Truncate long file names and add tooltip:
2. In Identity Dialog, limit _**Document name**_ string width and add tooltip on hover:
> Update Tooltip UI and truncate long file names in table in Local UI

- pebblo/app/pebblo-ui/src/components/bubbleChart.js
Bubble chart height to be dynamic:
1. Based on number of items in the input data
> Update bubble chart height to be dynamic

- pebblo/app/pebblo-ui/src/components/chartCard.js
Fixed an issue where if the app has one finding the bubble chart component throws error due to lack of 2 items in the array.
> Fix: single finding in bubble chart

- pebblo/app/daemon.py
- pebblo/topic_classifier/libs/logger.py
- pebblo/topic_classifier/topic_classifier.py
Because of this line in daemon.py
with redirect_stdout(StringIO()), redirect_stderr(StringIO()
logs and print statements were not working in the topic classifier because of which it was difficult to debug the classifier
On removing this line there were getting logs from "transformers" library. 
To suppress them code has been added in logger.py and warnings have been suppressed in topic_classifier.py
You can check the below image to see the difference
**Before** 
**After**
> Log and print statement were not working in topic classfiier

- pebblo/app/models/models.py
- pebblo/app/service/discovery_service.py
- tests/app/test_daemon.py
Sending ai_apps data including pebbloServerVersion and pebbloClientVersion in v1/app/discover API
Updated UTs as well
> Changes for showing pebblo server and client version on DAXA UI.

- pebblo/app/models/models.py
- pebblo/app/service/prompt_service.py
- tests/app/test_prompt_api.py
**Description:** There is a slight change in request and response structure format of _/v1/prompt_ API
**Updated Payload**
```
{
"name": "acme-corp-rag-123",
"context": [
{
"retrieved_from": "data_topic.csv",
"doc": "Sachin's SSN is 222-85. His AWS Access Key is: AKIPT4PDORIRTV6PH. His Passport ID is 5484880UA. And Github Token is: ghpu657yiujgwfrtigu3ver238765tyuhygvtrder6t7gyvhbuy5e676578976tyghy76578uygfyfgcyturtdf",
"vector_db": "ChromaDB"
},
{
"retrieved_from": "test_data.pdf",
"doc": "Sachin's SSN is 222-85. His AWS Access Key is: AKIPT4PDORIRTV6PH. His Passport ID is 5484880UA. And Github Token is: ghpu657yiujgwfrtigu3ver238765tyuhygvtrder6t7gyvhbuy5e676578976tyghy76578uygfyfgcyturtdf",
"vector_db": "ChromaDB234"
}
],
"prompt": {
"data": "What is Sachin's Name?"
},
"response": { …
```
> Changes in /prompt API

- pebblo_cloud/langchain/rag-sample/rag_sample.py
- pebblo_cloud/langchain/rag-sample/requirements.txt
- pebblo_cloud/langchain/rag-sample/semantic_rag_sample.py
- pebblo_safeloader/langchain/identity-rag/pebblo_identity_safeload.py
- pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py
- pebblo_saferetriever/langchain/identity-rag/requirements.txt
- pebblo_saferetriever/langchain/semantic-rag/pebblo_semantic_rag.py
- pebblo_saferetriever/langchain/semantic-rag/requirements.txt
We need the GoogleDriveLoader from the new repository (https://github.com/langchain-ai/langchain-google) to load authorized identities. It's not available in the GoogleDriveLoader within the Langchain community.
> Use GoogleDriveLoader from langchain_google_community

- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/app/routers/local_ui_routers.py
- pebblo/reports/html_to_pdf_generator/report_generator.py
- pebblo/reports/templates/weasyprintTemplate.html
- pebblo/reports/templates/xhtml2pdfTemplate.html
- tests/reports/test_report_generator.py
Fixes:
1. From identities dialog, disabled capitalize function on document name:
2. Removed timezone from date in xhtml2pdf and weasyprint report PDFs:
3. Added text wrap to long path names in both reports:
> Minor UI fixes

- pebblo/app/models/models.py
- pebblo/app/service/discovery_service.py
- pebblo/app/service/local_ui_service.py
- pebblo/app/service/prompt_service.py
- tests/app/service/test_discovery.py
Below are the fixes:
- Local UI backend : Replaced `retrieval` with `retrievals` in the app metadata file. For consistency of key name to be plural as it's list of retrievals.
- API Change: Upsert discovery details on top of retrieval details.
- Local UI backend : Fix for one error
Testing done:
- Tested with UI locally with latest UI changes.
> Safe retrieval fixes

- .github/workflows/linting.yml
Removing `codespell` until we find a way to exclude files (like .js)
> Remove spell check in CI lint pipeline

- pebblo/app/api/redirection_api.py
- pebblo/app/pebblo-ui/index.html
- pebblo/app/pebblo-ui/src/constants/routesConstant.js
- pebblo/app/pebblo-ui/src/services/get.js
Fixes:
1. Fix Pebblo UI '/' redirection to '/pebblo/'
2. Download report removed PROXY while generating the request URL and used window.location.origin + API endpoint instead.
> Pebblo redirection and download report URL fix

- pebblo_saferetriever/README.md
- pebblo_saferetriever/langchain/identity-n-semantic-rag/README.md
- pebblo_saferetriever/langchain/identity-n-semantic-rag/semantic_rag.py
- pebblo_saferetriever/langchain/identity-rag/README.md
- pebblo_saferetriever/langchain/identity-rag/pebblo_identity_rag.py
- pebblo_saferetriever/langchain/semantic-rag/README.md
- pebblo_saferetriever/langchain/semantic-rag/pebblo_semantic_rag.py
- Import PebbloRetrievalQA from langchain_community
- update auth context key `username` -> `user_id`
> Update samples: Import PebbloRetrievalQA from langchain_community

- pebblo/app/service/service.py
Before this fix:
After the fix:
This was not giving error because this is not mandatory param, but it is showing size as empty on UI.
> source_aggr_size renamed to source_aggregate_size in loader/doc API.

- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/app/pebblo-ui/src/util.js
Sort by date (most recent to least):
1. Active users table:
2. Documents table:
> Add sort by date recent for active users and docs

- docs/gh_pages/docs/retrieval_chain.md
Documentation for PebbloRetrievalQA chain
> Documentation for PebbloRetrievalQA chain

- .github/workflows/test_pypi_release.yml
Change the naming in test-pypi to a format similar to `pebblo-0.1.15.2024.5.6.1819-py3-none-any.whl` 
This fixes the problem where an older dev pkg is considered a latest even if a newer version is pushed to https://test.pypi.org/project/pebblo/#history
> Fix test pypi pkg naming to include yr.mo.dt.hh.mm

- docs/gh_pages/docs/rag.md
Add GoogleDriveLoader to the list of supported loaders by Pebblo
> Add GoogleDriveLoader to the list of supported loaders by Pebblo

- .github/workflows/tests.yml
Few UTs are failing on python 3.12.4. Ref - https://github.com/daxa-ai/pebblo/actions/runs/9609007513/job/26502752534
It is because of the compatibility with pydantic 1.10.4 version with python 3.12.4.
Executed UTs with python 3.12.3 and they are running fine.
In this PR, pinning python version to 3.12.3 untill pydantic version issue is resolved.
Local logs with python 3.12.3:
```
(venv-3.12.3) ➜  pebblo git:(main) ✗ make tests
pytest tests/ --durations=10
=========================================================================================== test session starts ============================================================================================
platform darwin -- Python 3.12.3, pytest-8.0.0, pluggy-1.5.0
rootdir: /Users/shreyasdamle/work/cloud_defense/shreyas-damle/pebblo …
```
> Pinned python 3.12 version for UTs

- docs/gh_pages/docs/rag.md
- docs/gh_pages/docs/retrieval_chain.md
Add Supported Loader(SharePointLoader) and Vector Database(Postgres PGVector)
> docs: Add SharePointLoader and Postgres PGVector supported list

- pebblo/app/pebblo-ui/src/constants/constant.js
- Removed text-capitalise on app names on Pebblo UI:
- Change table heading from "Application Name" to "Applications":
> Remove text-capitalise on app names on Pebblo UI

- pyproject.toml
Pinned `python-bidi` version to 0.4.2. It's new version 0.5.0 is creating problem and stopping generating pdf report.
`python-bidi` package is used by xhtml2pdf module.
Error with latest version of python-bidi:
```
No module named 'bidi.algorithm'
```
Tested locally with the pinned version. pdf report is getting generated.
Ref failure result link - https://github.com/daxa-ai/pebblo/actions/runs/10025055958/job/27707821834#step:12:109
> Pinned python-bidi version to 0.4.2

- pebblo/app/api/local_ui_api.py
- pebblo/app/routers/local_ui_routers.py
- pebblo/app/service/local_ui_service.py
- pebblo/app/utils/utils.py
- tests/app/test_utils.py
Ref - https://github.com/daxa-ai/pebblo/issues/368 - Add delete app.
**Note :** We have used `shutil` and `tempfile` modules. Both are python in-built modules and work on mac and linux.
> Add Delete App

- pyproject.toml
Updated fastapi, pydantic, transformers module versions as per dependabot findings.
Ref link for dependabot run before fixing these - https://github.com/daxa-ai/pebblo/security/dependabot?q=is%3Aopen+manifest%3Apyproject.toml
Verified few applications after version update. Checked Local UI and pdf reports.
> Fix Dependabot findings in Pebblo

- pyproject.toml
**Note:** Updating pebblo-version from `0.1.17-rc1` to `0.1.17rc1`, as it was failing UT. 
**Reason:** on `pyproject.toml` version is specified as  `0.1.17-rc1` , but while fetching version of pebblo using `importlib.metadata`  the version is coming as `0.1.17rc1` , as the pebblo version is being created with this name only without `-`. The wheel file is also without `-` -> `pebblo-0.1.17rc1-py3-none-any.whl`
> Updating pebblo version

- pebblo/app/pebblo-ui/index.html
Removed the meta tag for Content Security Policy : update-insecure-requests from index.html - which automatically upgrades any **_http_** requests to **_https_** requests.
> Pebblo UI : Fix http to https auto upgrade issue

- pebblo/app/service/local_ui_service.py
Loader Apps would be sorted based on total findings in it, as shown in the diagram:
> Sort Loader apps based on total findings

- pebblo/reports/templates/index.css
- pebblo/reports/templates/weasyprintTemplate.html
- pebblo/reports/templates/xhtml2pdfTemplate.html
Added work-break: all to columns in findings table:
**weasyprint report PDF:**
**xhtml2pdf report PDF:**
> Word break: all if overflows column width

- pebblo/app/models/models.py
- pebblo/app/service/local_ui_service.py
- pebblo/app/service/prompt_gov.py
- tests/app/service/test_prompt_gov.py
Added changes to add try-catch while retrieving data for retrieval apps
> Added changes for try catch in al app retrieval

- pebblo/app/service/doc_helper.py
- pebblo/app/service/prompt_gov.py
- pebblo/app/service/prompt_service.py
- pebblo/entity_classifier/README.md
- pebblo/entity_classifier/entity_classifier.py
- pebblo/entity_classifier/utils/utils.py
- pebblo/topic_classifier/README.md
- pebblo/topic_classifier/topic_classifier.py
- pebblo/utils.py
- tests/app/service/test_prompt_gov.py
- tests/entity_classifier/test_entity_classifier.py
- tests/test_utils.py
- tests/topic_classifier/test_topic_classifier.py
**Changes:**
- **Entity Classifier**
- Earlier it was sending `entities, count, input_text`
- Now it will send `entities, count, input_text, entity_details`
- e.g., 
- **input_text:** `Sachin's SSN is 222-85-4836.`
- **entities:** `{'us-ssn': 1}`
- **count:** `1`
- **entity_details:** `{'us-ssn': [{'location': '16_24', 'confidence_score': 'HIGH'}]}`
- **Topic Classifier**
-  Earlier it was only returning topic and its count
- Now it will return with confidence score:
- e.g.,
- **topics:** `{'financial-report': [{'confidence_score': 'HIGH'}]}`
- **count:** `1`
> Adding confidence score to entities and topic responses

- pebblo/app/models/models.py
- pebblo/app/service/doc_helper.py
- pebblo/app/service/local_ui_service.py
To display `client_version` on Pebblo Local UI, added `clientVersion` in model for loader as well as retriever app
> Adding client version to report.json file

- pebblo/app/models/models.py
- pebblo/app/service/doc_helper.py
- tests/app/service/test_loader_doc.py
Attaching one `report.json` file with `entityDetails` as well as `topicDetails` entry
[report.json](https://github.com/user-attachments/files/16578257/report.json)
> Changes for confidence score in /loader/doc as well as UI API

- pebblo/app/pebblo-ui/src/components/snippetDetails.js
- pebblo/app/pebblo-ui/src/components/tooltip.js
- pebblo/app/pebblo-ui/static/index.css
Add confidence score at snippet level for topics:
Increase width of tooltip for confidence score:
Backward compatibility (Do not show anything if no confidence score if found):
> Add confidence score at Snippet level

- docs/gh_pages/docusaurus.config.ts
> Pebblo Docs - Hide "Version not actively maintained" note

- pebblo/app/service/local_ui/loader_apps.py
- pebblo/app/service/prompt_service.py
- Fixed retrieval app blank issue
Before:
After:
- Fixed app name blank on Findings tab on Sage Loader Dashboard(see undefined vs app names in last column in the attached screenshots)
Before:
After :
> Retrieval App Bug Fix

- pebblo/app/pebblo-ui/src/components/progressBar.js
- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/reports/html_to_pdf_generator/report_generator.py
- pebblo/reports/templates/weasyprintTemplate.html
- pebblo/reports/templates/xhtml2pdfTemplate.html
- tests/reports/test_report_generator.py
Update Pebblo Client Version Key:
1. Pebblo Local UI:
2. Show pebbloClientVersion if client version does not exist (backward compatibility):
3. Reports -  weasyprint report PDF:
- Show nothing if client version does not exist (backward compatibility): 
4. Reports - xhtml2pdf report PDF:
- Show nothing if client version does not exist (backward compatibility):
> Update client version field in PDF reports and local UI app details page

- pebblo/app/service/local_ui/retriever_apps.py
**Issue:** Prompts with Findings for Safe Retriever Apps, was showing incorrect values.
**Reason:** It was overriding the value of previous app value in every iteration
**Error:**
**Fixed:**
> DB Retriever app prompt with findings fix

- docs/gh_pages/sidebars.ts
Add Langchain tab in Pebblo Docs:
> Add Langchain tab in Pebblo Docs

- pebblo/app/pebblo-ui/src/components/snippetDetails.js
Fixed issue: On using the search feature to search for labels, the snippet count was being updated incorrectly.
> Fix Snippets Listing Page - Snippets Count issue

- docs/gh_pages/docs/config.md
- pebblo/app/config/config_validation.py
Before removing deprecate warning:
```
(venv-3-11) ➜  pebblo git:(shreyas-documentation-changes) ✗ pebblo --config pebblo/app/config/config.yaml
0%|                                                                                                                                                                                | 0/10[00:00<?, ?it/s]
DeprecationWarning: 'file' Storage Type will be deprecated starting from Pebblo version 0.0.19, use 'db' instead
Pebblo server version 0.1.17 starting ...
Downloading topic, entity classifier models ...
```
After removing deprecate warning:
```
(venv-3-11) ➜  pebblo git:(shreyas-documentation-changes) ✗ pebblo --config pebblo/app/config/config.yaml
Pebblo server version 0.1.17 starting ...
Downloading topic, entity classifier models ...
```
> Documentation for storage type

- pebblo/app/service/doc_helper.py
- tests/app/service/test_loader_doc.py
**Issue:** In snippets in Safe Loader app, confidence score was highlighted for all the entities/topics, rather it should only be highlighted for the specific label
**Before**
**After**
> Confidence Score fix to highlight only the entity which is present in the label name

- Makefile
**Description:** 
- Ensure the build module is installed before running the build command.
- Currently, the `make install` command fails if the build module is not installed. We need to install it and rerun the install command manually.
- After this change, when a new Python environment is created, `make install` will be the only command needed to install Pebblo.
> Ensure the build module is installed before running build command

- pebblo/app/config/config.py
- pebblo/app/daemon.py
Fix for #515. 
Handles case when `--config` is unused -> where https://github.com/daxa-ai/pebblo/blob/f13be94416e60472d86e7fd24a628ec3b1be1d33/pebblo/app/config/config.py#L71C5-L71C16
will take `None` as its `path` argument, and the case where `--config` is passed but is not a valid path -> raises `FileNotFoundError`
> #515 raise if --config is passed but file does not exist

- pebblo/app/pebblo-ui/src/constants/keywordMapping.js
- pebblo/entity_classifier/utils/config.py
- pebblo/entity_classifier/utils/regex_pattern.py
- pebblo/reports/enums/keyword_mapping.py
**Added a new pii for Github Fine Grained Token** 
"""\b((?:github_pat)_[a-zA-Z0-9_]{36,255})\b"""
Adding github_pat as mentioned [here](https://github.com/odomojuli/regextokens) and based on test data we created.
**Slack**
Changed from  - """(xoxb|xoxp|xapp|xoxa|xoxr)\-[0-9]{10,13}\-[a-zA-Z0-9\-]*"""
To - """(xoxb|xoxp|xapp|xoxa|xoxr|xoxo|xoxs|xoxe)\-[0-9]{10,13}\-[a-zA-Z0-9\-]*"""
Adding as mentioned [here](https://learn.microsoft.com/en-us/purview/sit-defn-slack-access-token) 
**Google API**
Changed from  - """(?i)(?:youtube)(?:.|[\n\r]){0,40}\bAIza[0-9A-Za-z\-_]{35}\b"""
To  - """\bAIza[0-9A-Za-z\-_]{35}\b
Changing as mentioned [here](https://learn.microsoft.com/en-us/purview/sit-defn-google-api-key) 
Reducing confidence score from 0.8 to 0.4 for 
Github token
Github Finegrained Token …
> added changes for github and slack token

- pebblo/app/models/db_models.py
- pebblo/app/service/loader/loader_doc_service.py
- pebblo/app/service/loader/snippet/snippet.py
- pebblo/app/service/local_ui/loader_apps.py
Added confidence score functionality for apps with storage as DB
> Confidence score changes for DB

- pebblo/app/models/db_models.py
- pebblo/app/service/loader/document/document.py
- pebblo/app/service/loader/loader_doc_service.py
- pebblo/app/service/local_ui/loader_apps.py
- Added size param
- Added exception handling in local UI code.
> SQLite - Minor fixes

- pebblo/entity_classifier/utils/utils.py
**Issue:** The expected locations should be in ascending order in entity details  otherwise it truncates the string in between in local UI.
> Fix entity details response to return based on location order

- Makefile
**Description:**
The old command fails with newer versions of ruff. The new command is backward compatible and works with older(`ruff 0.4.2`) and newer(`ruff 0.6.3`) Ruff versions.
**1. Before and After output for new Ruff version(ruff 0.6.3, New Python 3.9 venv):**
**2. Before and After output for older Ruff version (ruff 0.4.2, Existing Python 3.9 venv):**
> Fix the ruff command error

- pebblo/app/enums/enums.py
- pebblo/app/models/db_models.py
- pebblo/app/models/sqltables.py
- pebblo/app/service/discovery/discovery_service.py
- pebblo/app/service/loader/document/document.py
- pebblo/app/service/loader/loader_doc_service.py
- pebblo/app/service/loader/snippet/snippet.py
- pebblo/app/service/local_ui/loader_apps.py
- pebblo/app/service/local_ui/retriever_apps.py
- pebblo/app/utils/utils.py
- Implemented load history.
- Handled "Findings" on "Documents With Findings" tab on application details page.  For this, one change needed on the `aidocument` table about adding findings count per entity/topic.
- Pydantic fixes needed due to upgrade to pydantic v2 => `dict()` to `model_dump()`.
- timeit() would run only when debug logs are enabled.
- Delete pdf report when delete app is called from UI.
> DB load history

- pebblo/app/pebblo-ui/src/components/snippetDetails.js
- pebblo/app/pebblo-ui/static/index.css
Fixed the issue where the snippet string was overflowing from the snippet details table.
> Fixed text overflow on snippet details "snippet" string

- pebblo/app/pebblo-ui/src/components/tab.js
- pebblo/app/pebblo-ui/src/constants/constant.js
- pebblo/app/pebblo-ui/static/index.css
Truncated data source path string to wrap onto the next line:
- <img width="1242" alt="image" src="https://github.com/user-attachments/assets/72184355-fde6-4a17-8643-4c9b64ceccbb">
- <img width="1244" alt="image" src="https://github.com/user-attachments/assets/a605ed8c-3c85-4d0c-825e-69340a7b055f">
> Fix Data source path overflow issue

- pebblo/app/pebblo-ui/src/constants/constant.js
Fix sorting on Findings - Total Column in Applications Table:
> Fix sorting on findings-total

- pebblo/app/api/req_models.py
- pebblo/app/service/doc_helper.py
- pebblo/app/service/service.py
- tests/app/service/test_loader_doc.py
Updated `/loader/doc` API based on classifier -> mode  value for storage type as `file`
> Adding classifier mode changes for file type storage

- .github/workflows/integration_run.yml
Integration tests were failing with below reason:
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. 
Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
Fixed it through this fix.
Verified by running pipeline on my branch - https://github.com/daxa-ai/pebblo/actions/runs/10825876391
> Fixed integration tests

- pebblo/app/pebblo-ui/src/components/applicationList.js
- pebblo/app/pebblo-ui/src/components/snippetDetails.js
- pebblo/reports/html_to_pdf_generator/report_generator.py
- tests/reports/test_report_generator.py
Addressed 3  issues of the following types:
1. Make sure that this dynamic injection or execution of code is safe: Refactored the filtering function on Applications List table and Snippets listing to prevent use of eval() in JS.
2. Make sure disabling auto-escaping feature is safe here: Added autoescape=jinja2.select_autoescape() to the Jinja2 Environment function to enable auto-escaping smartly for the given template file. All special characters would be rendered as strings.
> Fix Security Issues

- pebblo/app/api/req_models.py
- pebblo/app/models/db_models.py
- pebblo/app/service/discovery/discovery_service.py
- pebblo/app/service/discovery_service.py
**Issue:**
```
send_discover[local]: 
request url http://localhost:8000/v1/app/discover, 
body b'{"name": "acme-sharepoint-ai-search-loader-app-5-0.1.19qa", "owner": "ACME Corp", "description": "Identity enabled SafeLoader app using Pebblo", "load_id": "911875e8-1251-477e-bf32-00b0b889a613", "runtime": {"type": "desktop", "host": "Sridhars-MacBook-Pro.local", "path": "/Users/sridhar/pebblo/demos/pebblo-identityrag-sharepoint-0.1.17-qa", "ip": "127.0.0.1", "platform": "macOS-14.6.1-arm64-arm-64bit", "os": "Darwin", "os_version": "Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000", "language": "python", "language_version": "3.11.9", "runtime": "Mac OSX"}, "framework": {"name": "langchain", "version": "0.2.32"}, "plugin_version": "0.1.1"}' …
```
> Fixing client_version error

- Makefile
Currently, the Ruff formatter does not sort imports. We need to sort imports by calling the Ruff linter.
Ref: [https://docs.astral.sh/ruff/formatter/#sorting-imports](https://docs.astral.sh/ruff/formatter/#sorting-imports)
> Add Ruff sort imports command to the format_diff target

- .github/workflows/docker_multiarch_build.yaml
- .github/workflows/docker_release.yml
- deploy/docker/Dockerfile.base
Added manual workflow for older docker build.
> added multi-arch build for docker.

- docs/gh_pages/docs/entityclassifier.md
- pebblo/entity_classifier/README.md
- pebblo/entity_classifier/utils/config.py
- pebblo/entity_classifier/utils/regex_pattern.py
- tests/entity_classifier/mock_response.py
- tests/entity_classifier/test_data.py
- tests/entity_classifier/test_entity_classifier.py
- New field added client-secret for Azure client secret ID
- Also updated previous UTs for better accuracy.
- Updated docs as well as README
> New field added client-secret for Azure client secret ID.

- pebblo_safeloader/langchain/textloader_postgress/.env.sample
- pebblo_safeloader/langchain/textloader_postgress/pebblo_safeload.py
- pebblo_safeloader/langchain/textloader_postgress/requirements.txt
- pebblo_safeloader/langchain/textloader_postgress/util.py
Samples: text loader sample using PebbloTextLoader
> Samples: text loader sample using PebbloTextLoader

- pebblo/app/api/req_models.py
- pebblo/app/service/doc_helper.py
- pebblo/app/service/loader/loader_doc_service.py
- pebblo/app/service/service.py
- tests/app/service/test_doc_helper.py
- tests/app/service/test_loader_doc_service.py
- Added `anonymize_snippets` as new field in `/loader/doc` API.
- If `anonymize_snippets` is included in the API request, it will be used; otherwise, the value will be taken from config.
- Updated UTs
- Added type checking for previous code.
> Adding anonymize_snippet as a input filed in /loader/doc API

- pebblo/app/config/config_validation.py
- pebblo/app/enums/common.py
- tests/app/config/test_config_validation.py
If in config file, storage type is set as file belo message will be shown while running pebblo server:
`DeprecationWarning: 'file' in storage type is deprecated, use 'db' instead`
> Adding deprecation message for db storage type as file in config

- .github/workflows/integration_run.yml
Updated github action to run integration tests on different python version's with different langchain-community version's
Python versions: `"3.10.15", "3.11.10", "3.12.6"`
langchain-community-version: `"0.2.10", "0.2.12", "0.2.16", "0.3.0"`
With the above versions github action will run 12 times.
> Added the last released versions of langchain-community to run tests

- pebblo/app/config/config.py
While running pebblo server without config file, the default value was not getting returned with following error:
```
Error while loading config details, err: expected str, bytes or os.PathLike object, not NoneType
Exiting due to validation error...
```
Also, Added `anonymizeSnippets` in reports in default config
> Returning default value if no config path is passed

- pebblo/app/models/sqltables.py
- pebblo/app/service/local_ui/loader_apps.py
- pebblo/app/service/local_ui/retriever_apps.py
- pebblo/app/storage/sqlite_db.py
- tests/app/storage/test_sqlite_db.py
- tests/app/test_storage.py
This includes two fixes:
1. Query optimization, in order to reduce the execution time for loading UI.
2. Moved sqlalchemy logging only when logging level is set to debug. See logs below.
3. Added `timeit` function for 4 entry point UI functions. This can be used to see how long did it take for backend processing for data generating for dashboard(loader and retriever), app details page(loader and retriever). Time tracking would be done only when logging level is debug.
4. Fixed import warning.
Query Optimisation Results:
Here’s a table comparing the execution times before and after:
| **Function Name**                | **Execution Time (Before)**  | **Execution Time (After)**   |
|-----------------------------------|------------------------------|------------------------------|
| …
> DB query optimization and reducing sqlalchemy logs

- deploy/docker/config.yaml
- docs/gh_pages/docs/config.md
We are getting below warning with Pebblo:0.1.20 docker image
`DeprecationWarning: 'anonymizeSnippets' in classifier is deprecated, use 'anonymizeSnippets' in reports instead`.
With this code change, updated the config file.
Tested locally by building image.
> Updated config file for docker.

- .github/workflows/pypi_release.yml
Downgraded Twine Version to 6.0.1 for Pypi release. Since there was no version given in pypi_release.yaml it was installing Twine's latest version, and the workflow was breaking because of that.
> Downgraded Twine Version for pypi release
